import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/ui/Navbar";
import { Toaster } from "react-hot-toast";
import Providers from "@/app/components/Providers";
import { getUserCart } from "./_actions/cart.actions"
import { CartProvider } from "@/app/_context/CartContext"
import TopBar from "./components/TopBar"
import Footer from "./components/Footer"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

 const userCart = await getUserCart()

return (
  <html lang="en">
    <body
      className={`${geistSans.variable} ${geistMono.variable} min-h-screen flex flex-col`}
      suppressHydrationWarning
    >
      <Providers>
        <CartProvider
          initialNumberOfCartItems={userCart?.numOfCartItems ?? 0}
        >
          <TopBar />
          <Navbar />
          <Toaster position="top-center" />
          <div className="flex-1">{children}</div>
          <Footer />
        </CartProvider>
      </Providers>
    </body>
  </html>
);
}
